require("user.options")
require("user.keybinds")


require("user.plugins.colorscheme")
require("user.plugins.dashboard-nvim")
require("user.plugins.fzf")
require("user.plugins.nvim-tree")
require("user.plugins.oil-nvim")
require("user.plugins.aerial")
-- require("user.plugins.blink-cmp") -- Revisit once built-in completion is explored
require("user.plugins.diffview")
require("user.plugins.fidget")
require("user.plugins.gitsigns")
require("user.plugins.indent-blankline")
require("user.plugins.lualine")
require("user.plugins.neogit")
require("user.plugins.nvim-autopairs")
require("user.plugins.nvim-surround")
require("user.plugins.nvim-treesitter")
require("user.plugins.nvim-web-devicons")
require("user.plugins.render-markdown")
require("user.plugins.smart-splits")
require("user.plugins.text-case")
require("user.plugins.todo-comments")
require("user.plugins.toggleterm")

require("user.plugins.lsp-config")
require("user.lsp-keybinds")

